# Generated by Django 3.1 on 2020-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200921_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(default='', max_length=300),
        ),
    ]
